# In this directory, run the following command to build this builder.
# $ gcloud container builds submit . --config=cloudbuild.yaml

steps:

- name: 'gcr.io/cloud-builders/docker'
  id: 'Build application and container'
  args:
  - 'build'
  - '-t'
  - 'gcr.io/$PROJECT_ID/nodejs'
  - '.'

- name: 'gcr.io/cloud-builders/docker'
  id: 'Push image to Container Registry'
  args:
  - 'push'
  - 'gcr.io/$PROJECT_ID/nodejs'

# This step generates the new manifest
- name: 'gcr.io/cloud-builders/gcloud'
  id: Generate manifest
  entrypoint: /bin/sh
  args:
  - '-c'
  - |
     sed "s/${SHORT_SHA}/#VERSION/g" kubernetes/deployment.yaml"

- name: 'gcr.io/cloud-builders/kubectl'
  id: Deploy
  args:
  - 'apply'
  - '-f'
  - 'kubernetes'
  env:
  - 'CLOUDSDK_COMPUTE_REGION=us-central1-c'
  - 'CLOUDSDK_CONTAINER_CLUSTER=my-first-cluster-1'

options:
  logging: CLOUD_LOGGING_ONLY