# In this directory, run the following command to build this builder.
# $ gcloud container builds submit . --config=cloudbuild.yaml

steps:

- name: 'gcr.io/cloud-builders/docker'
  id: 'Build application and container'
  args:
  - 'build'
  - '-t'
  - 'gcr.io/$PROJECT_ID/nodejs'
  - '.'

- name: 'gcr.io/cloud-builders/docker'
  id: 'Push image to Container Registry'
  args:
  - 'push'
  - 'gcr.io/$PROJECT_ID/nodejs'

- name: 'gcr.io/cloud-builders/kubectl'
  id: 'Deploy to staging'
  args: ['apply', '-f', 'kubernetes/*']
  env:
  - 'CLOUDSDK_COMPUTE_REGION=$_COMPUTE_REGION'
  - 'CLOUDSDK_CONTAINER_CLUSTER=$_STAGING_CLUSTER'

options:
  logging: CLOUD_LOGGING_ONLY