apiVersion: v1
kind: Service
metadata:
  name: node-svc
  namespace: production
  labels:
    app: node-frontend
spec:
  selector:
    app: node-frontend
  ports:
  - port: 3000
    protocol: TCP
    nodePort: 30002
  type: LoadBalancer
