apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs
  namespace: develop
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: node-frontend
    spec:
      containers:
      - name: nodejs
        image: gcr.io/sunlit-mantra-367318/nodejs:1.0.0
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        resources:
            limits:
              cpu: "0.5"
              memory: "100mi"
            requests:
              cpu: "0.25"
              memory: "100mi"
