apiVersion: v1
kind: Service
metadata:
  name: node-svc
  namespace: develop
  labels:
    app: node-frontend
spec:
  selector:
    app: node-frotend
  ports:
  - port: 3000
    protocol: TCP
    nodePort: 30001
  type: LoadBalancer
